Repository GoogleChromeLabs/ps-analysis-tool, pull requests merged in 2024-05, with the labels that each got.

#646 Feature: Add HTML report generation to CLI dashboard and CLI
  dashboard.webpack.config.cjs
  extension.webpack.config.cjs
  package-lock.json
  package.json
  packages/cli-dashboard/src/components/utils/reportDownloader/generateSiteMapReportandDownload.ts
  packages/cli-dashboard/src/components/utils/reportDownloader/utils.ts
  packages/cli/src/index.ts
  packages/design-system/src/components/cookieTable/tests/index.tsx
  packages/design-system/src/components/table/components/filtersSidebar/tests/filtersSidebar.tsx
  packages/extension/babel.config.cjs
  packages/extension/package.json
  packages/extension/src/utils/generateReportObject.ts
  packages/extension/src/utils/tests/data.mock.ts
  packages/extension/src/view/devtools/components/settings/components/tests/informationContainer.tsx
  packages/extension/src/view/devtools/components/settings/components/tests/settingsContainer.tsx
  packages/extension/src/view/devtools/components/settings/tests/index.tsx
  packages/extension/src/view/devtools/components/siteBoundaries/tests/index.tsx
  packages/extension/src/view/devtools/tests/app.tsx
  packages/extension/src/view/report/components/blockedCookiesSection.tsx
  packages/report/README.md
  packages/report/babel.config.cjs
  packages/report/package.json
  packages/report/public/index.html
  packages/report/src/app.css
  packages/report/src/app.tsx
  packages/report/src/components/blockedCookiesSection.tsx
  packages/report/src/components/cookiesSection.tsx
  packages/report/src/components/exemptedCookiesSection.tsx
  packages/report/src/components/framesSection.tsx
  packages/report/src/components/index.ts
  packages/report/src/index.tsx
  packages/report/src/stateProviders/data/context.ts
  packages/report/src/stateProviders/data/dataProvider.tsx
  packages/report/src/stateProviders/data/index.ts
  packages/report/src/stateProviders/data/useData.ts
  packages/report/src/tests/app.tsx
  packages/report/src/tests/data.mock.ts
  packages/report/tsconfig.json
Labels: CLI

#685 Feature: Navigate from PSAT to network panel
  packages/extension/src/view/devtools/components/cookies/cookiesListing/rowContextMenu.tsx
  packages/extension/src/view/devtools/components/cookies/tests/rowContextMenu.tsx
Labels: enhancement

#692 Fix: Persist filters after web page reload
  packages/common/src/index.ts
  packages/common/src/utils/mergeDeep.ts
  packages/common/src/utils/tests/mergeDeep.ts
  packages/design-system/src/components/table/persistentSettingsStore/utils/updateStorage.ts
  packages/design-system/src/components/table/useTable/types.ts
  packages/design-system/src/components/table/useTable/useFiltering/hooks/index.ts
  packages/design-system/src/components/table/useTable/useFiltering/hooks/tests/useFiltersExtraction.tsx
  packages/design-system/src/components/table/useTable/useFiltering/hooks/tests/useFiltersOptions.tsx
  packages/design-system/src/components/table/useTable/useFiltering/hooks/useFiltersExtraction.tsx
  packages/design-system/src/components/table/useTable/useFiltering/hooks/useFiltersOptions.tsx
  packages/design-system/src/components/table/useTable/useFiltering/hooks/useFiltersPersistence.tsx
  packages/design-system/src/components/table/useTable/useFiltering/index.tsx
Labels: bug

#691 Fix: Exemption section disappearing
  packages/common/src/utils/parseRequestWillBeSentExtraInfo.ts
  packages/common/src/utils/parseResponseReceivedExtraInfo.ts
Labels: bug

#684 Fix: GSI messaging on correct urls.
  packages/library-detection/src/core/hooks/useLibraryDetection.ts
  packages/library-detection/src/core/stateProvider/index.tsx
Labels: bug

#683 Fix: inconsistent highlighting on livemint.com
  packages/cli/src/utils/browserManagement/parseNetworkDataToCookieData.ts
Labels: bug, CLI
