Repository GoogleChromeLabs/ps-analysis-tool, pull requests merged in 2024-02, with the labels that each got.

#463 Remove topics list feature
  data/topics-taxonomy-v1.json
  packages/extension/src/@types/index.d.ts
  packages/extension/src/contentScript/index.ts
  packages/extension/src/localStore/cookieStore.ts
  packages/extension/src/utils/fetchTopicsTaxonomy.ts
  packages/extension/src/view/devtools/components/privateAdvertising/topics/index.tsx
  packages/extension/src/view/devtools/components/privateAdvertising/topics/topicsList.tsx
Labels: bug

#436 Feature: Optimise cookie updating iterations to reduce the cookie loading time.
  packages/common/src/utils/getCookieKey.ts
  packages/common/src/utils/parseRequestWillBeSentExtraInfo.ts
  packages/common/src/utils/parseResponseReceivedExtraInfo.ts
  packages/design-system/src/components/table/components/index.tsx
  packages/extension/src/contentScript/index.ts
  packages/extension/src/localStore/cookieStore.ts
  packages/extension/src/localStore/preferenceStore.ts
  packages/extension/src/localStore/tests/cookieStore.ts
  packages/extension/src/serviceWorker/createCookieObject.ts
  packages/extension/src/serviceWorker/findPreviousCookieDataObject.ts
  packages/extension/src/serviceWorker/index.ts
  packages/extension/src/serviceWorker/parseRequestCookieHeader.ts
  packages/extension/src/serviceWorker/parseResponseCookieHeader.ts
  packages/extension/src/serviceWorker/tests/parseRequestCookieHeader.ts
  packages/extension/src/serviceWorker/tests/parseResponseCookieHeader.ts
  packages/extension/src/store/chromeStorage.ts
  packages/extension/src/store/index.ts
  packages/extension/src/store/synchnorousCookieStore.ts
  packages/extension/src/store/tests/synchnorousCookieStore.ts
  packages/extension/src/store/tests/updateStorage.ts
  packages/extension/src/store/types.ts
  packages/extension/src/store/utils/getIndexForAllowListedItem.ts
  packages/extension/src/store/utils/updateCookieBadgeText.ts
  packages/extension/src/store/utils/updateStorage.ts
  packages/extension/src/utils/addAuditsIssues.ts
  packages/extension/src/utils/canProcessCookies.ts
  packages/extension/src/utils/fetchCookieDictionary.ts
  packages/extension/src/utils/getCurrentTabId.ts
  packages/extension/src/utils/setDocumentCookies.ts
  packages/extension/src/utils/test-data/cookieMockData.ts
  packages/extension/src/utils/tests/canProcessCookies.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/onAllowListClick.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/removeFromAllowList.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/setDomainsInAllowList.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/setParentDomain.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/index.tsx
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/tests/useCookieListing.tsx
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/tests/useHighlighting.tsx
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/useHighlighting.tsx
  packages/extension/src/view/devtools/components/cookies/index.tsx
  packages/extension/src/view/devtools/hooks/useFrameOverlay.ts
  packages/extension/src/view/devtools/stateProviders/syncCookieStore/index.tsx
  packages/extension/src/view/devtools/stateProviders/syncSettingsStore/index.tsx
  packages/extension/src/view/devtools/tests/app.tsx
  packages/extension/src/view/popup/stateProviders/syncCookieStore/index.tsx
  packages/extension/src/view/popup/stories/app.stories.tsx
  packages/extension/src/view/popup/tests/index.tsx
Labels: enhancement, Performance

#455 Feature: Make CLI dashboard filters dynamic
  packages/cli-dashboard/src/components/affectedCookies/index.tsx
  packages/cli-dashboard/src/components/siteReport/tabs/cookies/cookiesListing/index.tsx
  packages/cli-dashboard/src/hooks/useCookieListing.tsx/index.tsx
  packages/cli-dashboard/src/hooks/useCookieListing.tsx/utils/calculateBlockedReasonsFilterValues.tsx
  packages/cli-dashboard/src/hooks/useCookieListing.tsx/utils/calculateDynamicFilterValues.ts
  packages/cli-dashboard/src/hooks/useCookieListing.tsx/utils/tests/calculateBlockedReasonsFilterValues.ts
  packages/cli-dashboard/src/hooks/useCookieListing.tsx/utils/tests/calculateDynamicFilterValues.ts
  packages/common/src/constants/index.ts
  packages/design-system/src/components/table/components/tableBody/bodyRow.tsx
Labels: CLI

#484 Fix: Slow loading cookies on page change
  packages/extension/src/manifest.json
  packages/extension/src/store/synchnorousCookieStore.ts
Labels: Cookies

#518 Fix: Allow listed rows to highlight after frame change
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/useHighlighting.tsx
Labels: bug

#531 Fix: Allow listed rows to highlight after frame change
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/useHighlighting.tsx
Labels: bug
