Repository GoogleChromeLabs/ps-analysis-tool, pull requests merged in 2024-12, with the labels that each got.

#877 Address package vulnerabilities and dependency updates
  package-lock.json
Labels: dependencies

#886 Remove validatejs and use custom validator.
  package-lock.json
  packages/extension/package.json
  packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/jsonGenerator/utils/validateContactEmail.ts
  packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/jsonGenerator/utils/validateRationale.ts
  packages/extension/src/view/devtools/components/siteBoundaries/relatedWebsiteSets/jsonGenerator/utils/validateUrl.ts
Labels: dependencies

#900 Fix: Allow changes E2E run against develop main and release branches.
  .github/workflows/tests-cli-e2e-tests.yml
  .github/workflows/tests-extension-e2e-tests.yml
  packages/extension/src/view/devtools/e2e-tests/landingPages/index.ts
Labels: Code Quality

#902 Feature: Implement p5 workflow
  ee-workflow/index.html
  ee-workflow/package-lock.json
  ee-workflow/package.json
  ee-workflow/public/vite.svg
  ee-workflow/src/components/animator.ts
  ee-workflow/src/components/figure/box.ts
  ee-workflow/src/components/figure/circle.ts
  ee-workflow/src/components/figure/image.ts
  ee-workflow/src/components/figure/index.ts
  ee-workflow/src/components/figure/line.ts
  ee-workflow/src/components/figure/text.ts
  ee-workflow/src/components/group.ts
  ee-workflow/src/index.ts
  ee-workflow/src/main.ts
  ee-workflow/src/typescript.svg
  ee-workflow/src/vite-env.d.ts
  ee-workflow/tsconfig.json
Labels: Architecture
