Repository GoogleChromeLabs/ps-analysis-tool, pull requests merged in 2024-01, with the labels that each got.

#211 Quickly Launch Different Chrome for Privacy Sandbox Demo
  bin/chrome-3pcd-ps.bat
  bin/chrome-3pcd.bat
  bin/chrome-chip.bat
  bin/chrome-default-ps.bat
  bin/chrome-default.bat
  bin/chrome-psat.bat
  bin/chrome_launcher.sh
  bin/install.sh
Labels: P0, PSAT

#425 Feature: Detect use of Google Sign In (GSI) libraries
  package-lock.json
  packages/common/src/index.ts
  packages/common/src/libraryDetection.types.ts
  packages/common/src/worker/devToolWorker.ts
  packages/common/src/worker/enums.ts
  packages/common/src/worker/executeTaskInDevToolWorker.ts
  packages/design-system/src/components/cookiesLanding/cookieLandingHeaderContainer.tsx
  packages/design-system/src/components/cookiesLanding/index.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/progressBar/borderProgressbar.tsx
  packages/extension/package.json
  packages/extension/src/view/devtools/components/cookies/index.tsx
  packages/extension/src/view/devtools/index.tsx
  packages/extension/src/worker/index.ts
  packages/extension/webpack.config.cjs
  packages/library-detection/README.md
  packages/library-detection/package.json
  packages/library-detection/src/components/accordion/accordionContent.tsx
  packages/library-detection/src/components/accordion/accordionHeading.tsx
  packages/library-detection/src/components/accordion/featureList.tsx
  packages/library-detection/src/components/accordion/index.tsx
  packages/library-detection/src/components/index.tsx
  packages/library-detection/src/components/libraryDetection/index.tsx
  packages/library-detection/src/config.ts
  packages/library-detection/src/core/detectMatchingSignatures.ts
  packages/library-detection/src/core/filterResources.ts
  packages/library-detection/src/core/getHelpUrl.ts
  packages/library-detection/src/core/getInlineScriptContent.ts
  packages/library-detection/src/core/hooks/useLibraryDetection.ts
  packages/library-detection/src/core/index.ts
  packages/library-detection/src/core/isRequestURLMatchingDomainPaths.ts
  packages/library-detection/src/core/stateProvider/index.tsx
  packages/library-detection/src/core/sumUpDetectionResults.ts
  packages/library-detection/src/core/tests/filterResources.ts
  packages/library-detection/src/core/tests/getHelpUrl.ts
  packages/library-detection/src/core/tests/getInlineScriptContent.ts
  packages/library-detection/src/core/tests/isRequestURLMatchingDomainPaths.ts
  packages/library-detection/src/core/tests/sumUpDetectionResults.ts
  packages/library-detection/src/index.ts
  packages/library-detection/src/libraries/gis/accordion.tsx
  packages/library-detection/src/libraries/gis/checkForGIS.ts
  packages/library-detection/src/libraries/gis/constants.ts
  packages/library-detection/src/libraries/gsi/accordion.tsx
  packages/library-detection/src/libraries/gsi/checkForGSIv2.ts
  packages/library-detection/src/libraries/gsi/constants.ts
  packages/library-detection/src/libraries/gsi/generateGSIV2Matches.ts
  packages/library-detection/src/libraries/index.tsx
  packages/library-detection/src/types.ts
  packages/library-detection/src/utils/getNetworkResourcesWithContent.ts
  packages/library-detection/src/utils/getResourcesWithContent.ts
  packages/library-detection/src/utils/index.ts
  packages/library-detection/src/utils/sourceMapGenerator.ts
  packages/library-detection/src/worker/constants.ts
  packages/library-detection/src/worker/index.ts
  packages/library-detection/tsconfig.json
  tailwind.config.cjs
Labels: feature

#376 Feature: Add the capability of setting "allow list" content policy
  packages/common/src/cookies.types.ts
  packages/design-system/src/components/cookieDetails/details.tsx
  packages/design-system/src/components/cookieTable/index.tsx
  packages/design-system/src/components/table/components/index.tsx
  packages/design-system/src/components/table/components/tableBody/bodyCell.tsx
  packages/design-system/src/components/table/components/tableBody/bodyRow.tsx
  packages/design-system/src/components/table/components/tableBody/index.tsx
  packages/design-system/src/components/table/components/tableBody/tests/bodyCell.tsx
  packages/design-system/src/components/table/components/tableBody/tests/bodyRow.tsx
  packages/design-system/src/components/table/components/tableBody/tests/index.tsx
  packages/design-system/src/test-data/cookieTableBody.ts
  packages/design-system/src/test-data/cookieTableMockData.tsx
  packages/extension/src/localStore/cookieStore.ts
  packages/extension/src/localStore/types.ts
  packages/extension/src/localStore/utils/getIndexForAllowListedItem.ts
  packages/extension/src/manifest.json
  packages/extension/src/serviceWorker/index.ts
  packages/extension/src/utils/reloadCurrentTab.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/index.tsx
  packages/extension/src/view/devtools/components/cookies/cookiesListing/rowContextMenu.tsx
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/getDotPrefixedDomain.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/index.tsx
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/isCookieDomainInAllowList.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/onAllowListClick.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/removeFromAllowList.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/setDomainsInAllowList.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/setParentDomain.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/tests/onAllowListClick.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/tests/setDomainsInAllowList.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/tests/setParentDomain.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/index.tsx
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/tests/useHighlighting.tsx
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/useHighlighting.tsx
  packages/extension/src/view/devtools/components/cookies/tests/rowContextMenu.tsx
  tailwind.config.cjs
Labels: feature

#460 Fix miscellaneous allow list QA issues
  packages/extension/src/serviceWorker/index.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/rowContextMenu.tsx
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/isCookieDomainInAllowList.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useAllowedList/setParentDomain.ts
  packages/extension/src/view/devtools/components/cookies/cookiesListing/useCookieListing/useHighlighting.tsx
  packages/extension/src/view/devtools/components/cookies/tests/rowContextMenu.tsx
Labels: bug
